spring:
 cloud:
   gateway:
    default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
    routes:
      
       - id: recruiter-service
         uri: lb://RECRUITER-SERVICE
         predicates:
            - Path=/api/jobcreation/**, /job/joblisting/**,/api/template/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
          - Path=/reset-password/**, /auth/**, /user/**

 application:
   name: XSEED-API-GATEWAY
   
server:
  port: 8085
   
   

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
